# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fGm <- function(dnm, Nm) {
    .Call(`_PartialNetwork2_fGm`, dnm, Nm)
}

fcpal0_1 <- function(alpha, R, distr, Ilist, y, Gy, X, GX, Kx, Kx1, Kx2, M, Ncum, FE = FALSE) {
    .Call(`_PartialNetwork2_fcpal0_1`, alpha, R, distr, Ilist, y, Gy, X, GX, Kx, Kx1, Kx2, M, Ncum, FE)
}

efcpal0_1 <- function(alpha, R, distr, Ilist, y, Gy, X, GX, Kx, Kx1, Kx2, M, Ncum, FE = FALSE) {
    .Call(`_PartialNetwork2_efcpal0_1`, alpha, R, distr, Ilist, y, Gy, X, GX, Kx, Kx1, Kx2, M, Ncum, FE)
}

fcpal0_0 <- function(alpha, R, distr, Ilist, y, Gy, X, Kx, M, Ncum, FE = FALSE) {
    .Call(`_PartialNetwork2_fcpal0_0`, alpha, R, distr, Ilist, y, Gy, X, Kx, M, Ncum, FE)
}

efcpal0_0 <- function(alpha, R, distr, Ilist, y, Gy, X, Kx, M, Ncum, FE = FALSE) {
    .Call(`_PartialNetwork2_efcpal0_0`, alpha, R, distr, Ilist, y, Gy, X, Kx, M, Ncum, FE)
}

fcpal1_1 <- function(alpha, R, distr, Ilist, y, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_fcpal1_1`, alpha, R, distr, Ilist, y, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE, S)
}

efcpal1_1 <- function(alpha, R, distr, Ilist, y, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_efcpal1_1`, alpha, R, distr, Ilist, y, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE, S)
}

fcpal1_0 <- function(alpha, R, distr, Ilist, y, X, Kx, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_fcpal1_0`, alpha, R, distr, Ilist, y, X, Kx, M, Ncum, FE, S)
}

efcpal1_0 <- function(alpha, R, distr, Ilist, y, X, Kx, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_efcpal1_0`, alpha, R, distr, Ilist, y, X, Kx, M, Ncum, FE, S)
}

fcpal2_1 <- function(alpha, R, distr, Ilist, y, Gy, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_fcpal2_1`, alpha, R, distr, Ilist, y, Gy, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE, S)
}

efcpal2_1 <- function(alpha, R, distr, Ilist, y, Gy, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE = FALSE, S = 1L) {
    .Call(`_PartialNetwork2_efcpal2_1`, alpha, R, distr, Ilist, y, Gy, X, X1, GX1, X2, Kx, Kx1, Kx2, M, Ncum, FE, S)
}

